config/routes.rb
Shopmanager::Application.routes.draw do
  devise_for :market_users
  devise_for :courier_profiles
  devise_for :my_couriers
  devise_for :couriers
  resources :couriers_lists

  resources :curiers_lists

  resources :td_couriers

  resources :waybills_names
  post "waybills_names/add_relation"
  post "waybills_names/remove_relation"
  post "waybills_names/add_auto_courier"
  post "waybills_names/set_status"
  post "waybills_names/get_courier_loc"

  resources :waybills

  get "market_placemanage/main"
  get "market_placemanage/followers"
  get "market_placemanage/orders"
  get "market_placemanage/category_manage"
  get "market_placemanage/item_manage"
  get "market_placemanage/settings"
  get "market_placemanage/courier_manage"
  resources :tags

  get "public_tp/show"
  get "public_tp/trade"
  get "public_tp/review"
  get "market_manage/search_tp"
  get "market_manage/list_td"
  get "market_manage/orders"
  get "market_manage/settings"
  get "market_manage/add_tp"

  resources :card_markets

  resources :card_trading_platforms

  resources :markets

  resources :categories

  resources :items

  resources :types

  resources :orders
  post "orders/add_order"

  resources :couriers

  resources :autos

  get "default_pages/login"
  get "default_pages/market"
  get "market" => "default_pages#market"
  get "trader" => "default_pages#login"
  devise_for :users
  get "persons/profile"
  get "persons/market_profile"
  get "persons/market"
  get "persons/courier"
  get "persons/marketPlace"
  resources :marketplaces

  resources :users

  # The priority is based upon order btn btn-primaryof creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'default_pages#login'

  get 'persons/profile', as: 'user_root'

  get 'persons/market_profile', as: 'market_user_root'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/auto.rb
class Auto < ActiveRecord::Base
end

app/models/c_a_relations.rb
class CARelations < ActiveRecord::Base
end

app/models/card_market.rb
class CardMarket < ActiveRecord::Base
  has_attached_file :avatar
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/courier.rb
class Courier < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_attached_file :image
end

app/models/market.rb
class Market < ActiveRecord::Base
end

app/models/market_user.rb
class MarketUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/marketplace.rb
class Marketplace < ActiveRecord::Base
end

app/models/my_courier.rb
class MyCourier < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/td_courier.rb
class TdCourier < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/waybill.rb
class Waybill < ActiveRecord::Base
end

app/controllers/market_manage_controller.rb
class MarketManageController < ApplicationController
  def search_tp
    if params[:name]
      @marketPlaces = Marketplace.find_all_by_name(params[:name])
    end
  end

  def list_td
    @relations = TpAndMarketRelation.find_all_by_m_id(params[:m_id])
  end

  def orders
    @orders = Order.find_all_by_c_a_r_id(params[:m_id])
  end

  def settings
  end

  def add_tp
    relation = TpAndMarketRelation.new()
    relation.m_id = params[:m_id]
    relation.tp_id = params[:td_id]
    relation.save
    render :layout => nil

  end
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/market_manage_helper.rb
module MarketManageHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/market_manage/list_td.html.erb
<% if @relations  %>
    <h3>Торговые площадки</h3>
    <% @relations.each do |marketPlace| %>
        <% tp = Marketplace.find(marketPlace.tp_id) %>
        <a href="<%= public_tp_show_url%>?id=<%= tp.id %>&m_id=<%= params[:m_id] %>"> <div class="market_blocks"><h5 class="title"><%= tp.name %></h5><%= image_tag('biznes.jpg' , :class => 'icon') %> </div></a>

    <% end %>
<% end %>

app/views/market_manage/orders.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:Торговая_база) %></th>
    <th><%= model_class.human_attribute_name(:Магазин) %></th>
    <th><%= model_class.human_attribute_name(:Название_товара) %></th>
    <th><%= model_class.human_attribute_name(:Количество) %></th>
    <th><%= model_class.human_attribute_name(:Описание) %></th>
    <th><%= model_class.human_attribute_name(:Статус) %></th>
    <th><%= model_class.human_attribute_name(:Создан) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, order_path(order) %></td>
        <td><%= Marketplace.find(order.mp_id).name %></td>
        <td><%= Market.find(order.c_a_r_id).name %></td>
        <td><%= Item.find(order.item_id).name %></td>
        <td><%= order.count %></td>
        <td><%= order.description %></td>
        <td><% if order.status == 0 %>
              Не доставлен
          <% else  %>
              Доставлен
          <% end %></td>
        <td><%=l order.created_at %></td>
        <td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/market_manage/search_tp.html.erb
<form action="<%= market_manage_search_tp_url %>" method="GET">
  Название торговой базы <INPUT NAME="name">
  <input type="hidden" name="m_id" value="<%= params[:m_id] %>">

<INPUT TYPE=SUBMIT class="btn btn-primary" value="Найти">
</form>

<% if @marketPlaces  %>
    <h3>Торговые площадки</h3>
    <% @marketPlaces.each do |marketPlace| %>

        <a href="<%= public_tp_show_url%>?id=<%= marketPlace.id %>&m_id=<%= params[:m_id] %>"> <div class="market_blocks"><h5 class="title"><%= marketPlace.name %></h5><%= image_tag('biznes.jpg' , :class => 'icon') %> </div></a>

    <% end %>
<% end %>

app/views/market_manage/settings.html.erb
<h1>MarketManage#settings</h1>
<p>Find me in app/views/market_manage/settings.html.erb</p>