config/routes.rb
Shopmanager::Application.routes.draw do
  devise_for :market_users
  devise_for :courier_profiles
  devise_for :my_couriers
  devise_for :couriers
  resources :couriers_lists

  resources :curiers_lists

  resources :td_couriers

  resources :waybills_names
  post "waybills_names/add_relation"
  post "waybills_names/remove_relation"
  post "waybills_names/add_auto_courier"
  post "waybills_names/set_status"
  post "waybills_names/get_courier_loc"

  resources :waybills

  get "market_placemanage/main"
  get "market_placemanage/followers"
  get "market_placemanage/orders"
  get "market_placemanage/category_manage"
  get "market_placemanage/item_manage"
  get "market_placemanage/settings"
  get "market_placemanage/courier_manage"
  resources :tags

  get "public_tp/show"
  get "public_tp/trade"
  get "public_tp/review"
  get "market_manage/search_tp"
  get "market_manage/list_td"
  get "market_manage/orders"
  get "market_manage/settings"
  get "market_manage/add_tp"

  resources :card_markets

  resources :card_trading_platforms

  resources :markets

  resources :categories

  resources :items

  resources :types

  resources :orders
  post "orders/add_order"

  resources :couriers

  resources :autos

  get "default_pages/login"
  get "default_pages/market"
  get "market" => "default_pages#market"
  get "trader" => "default_pages#login"
  devise_for :users
  get "persons/profile"
  get "persons/market_profile"
  get "persons/market"
  get "persons/courier"
  get "persons/marketPlace"
  resources :marketplaces

  resources :users

  # The priority is based upon order btn btn-primaryof creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'default_pages#login'

  get 'persons/profile', as: 'user_root'

  get 'persons/market_profile', as: 'market_user_root'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/auto.rb
class Auto < ActiveRecord::Base
end

app/models/c_a_relations.rb
class CARelations < ActiveRecord::Base
end

app/models/card_market.rb
class CardMarket < ActiveRecord::Base
  has_attached_file :avatar
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/courier.rb
class Courier < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_attached_file :image
end

app/models/market.rb
class Market < ActiveRecord::Base
end

app/models/market_user.rb
class MarketUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/marketplace.rb
class Marketplace < ActiveRecord::Base
end

app/models/my_courier.rb
class MyCourier < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/td_courier.rb
class TdCourier < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/waybill.rb
class Waybill < ActiveRecord::Base
end

app/controllers/public_tp_controller.rb
class PublicTpController < ApplicationController
  def show
    @marketPlace = Marketplace.find(params[:id])
  end

  def trade
    if params[:id]
      @categories = Category.where(td_id: params[:td_id], parentCat: params[:id] )
      @items = Item.where(id_td: params[:td_id] , category_id: params[:id] )
      @m_id = params[:td_id]
    else
      @categories = Category.where(td_id: params[:td_id] , parentCat: 0 )
      @items = Item.where(id_td: params[:td_id] , category_id: 0 )
      @m_id = params[:td_id]
    end
  end

  def review
  end
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/public_tp_helper.rb
module PublicTpHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/public_tp/review.html.erb
<h1>PublicTp#review</h1>
<p>Find me in app/views/public_tp/review.html.erb</p>

app/views/public_tp/show.erb
<a href="<%= public_tp_show_url %>/<%= @marketPlace.id %>"> <div class="market_blocks"><h5 class="title"><%= @marketPlace.name %></h5><%= image_tag('biznes.jpg' , :class => 'icon') %> </div></a>
<% col = TpAndMarketRelation.where(m_id: params[:m_id] , tp_id: @marketPlace.id ).take
   if !col %>
<form action="<%= market_manage_add_tp_path %>?td_id=<%= @marketPlace.id %>&m_id=<%= params[:m_id]%>" class="button_to" data-remote="true" method="get">
  <div><input type="submit" value="Добавить" class="btn btn-primary"></div>
</form>
  <% else %>
    <h5>Вы добавили эту базу</h5>
  <% end %>
<a href="<%= public_tp_trade_url %>?td_id=<%= @marketPlace.id %>&m_id=<%= params[:m_id] %>">Товары торговой базы</a>

app/views/public_tp/trade.html.erb
<% @categories.each do |category| %>

    <a href="<%= public_tp_trade_url%>?id=<%=category.id %>&td_id=<%= @m_id %>&m_id=<%= params[:m_id] %>"><%= category.name %></a> <br>

<% end %>




        <% @items.each do |item| %>
        <tr>
          <td><%= image_tag(item.image.url, :class => 'items_image') %></td>

          <td><%= item.name %></td>

          <td><%= item.price %></td>
          <td><%= item.currency %></td>
          <td><%= item.count %></td>
          <td><%= item.description %></td>
          <td>
            <form action="<%= orders_add_order_url %>" class="button_to" data-remote="true" method="post">
              <input type="hidden" name="tp_id" value="<%= @m_id %>"/>
              <input type="hidden" name="m_id" value="<%= params[:m_id] %>"/>
              <input type="hidden" name="item_id" value="<%= item.id %>"/>
              <div><input type="submit" value="Добавить" class="btn btn-primary"></div>
            </form>

          </td>
        </tr>

    </tr>
<% end %>