config/routes.rb
Shopmanager::Application.routes.draw do
  devise_for :market_users
  devise_for :courier_profiles
  devise_for :my_couriers
  devise_for :couriers
  resources :couriers_lists

  resources :curiers_lists

  resources :td_couriers

  resources :waybills_names
  post "waybills_names/add_relation"
  post "waybills_names/remove_relation"
  post "waybills_names/add_auto_courier"
  post "waybills_names/set_status"
  post "waybills_names/get_courier_loc"

  resources :waybills

  get "market_placemanage/main"
  get "market_placemanage/followers"
  get "market_placemanage/orders"
  get "market_placemanage/category_manage"
  get "market_placemanage/item_manage"
  get "market_placemanage/settings"
  get "market_placemanage/courier_manage"
  resources :tags

  get "public_tp/show"
  get "public_tp/trade"
  get "public_tp/review"
  get "market_manage/search_tp"
  get "market_manage/list_td"
  get "market_manage/orders"
  get "market_manage/settings"
  get "market_manage/add_tp"

  resources :card_markets

  resources :card_trading_platforms

  resources :markets

  resources :categories

  resources :items

  resources :types

  resources :orders
  post "orders/add_order"

  resources :couriers

  resources :autos

  get "default_pages/login"
  get "default_pages/market"
  get "market" => "default_pages#market"
  get "trader" => "default_pages#login"
  devise_for :users
  get "persons/profile"
  get "persons/market_profile"
  get "persons/market"
  get "persons/courier"
  get "persons/marketPlace"
  resources :marketplaces

  resources :users

  # The priority is based upon order btn btn-primaryof creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'default_pages#login'

  get 'persons/profile', as: 'user_root'

  get 'persons/market_profile', as: 'market_user_root'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/auto.rb
class Auto < ActiveRecord::Base
end

app/models/c_a_relations.rb
class CARelations < ActiveRecord::Base
end

app/models/card_market.rb
class CardMarket < ActiveRecord::Base
  has_attached_file :avatar
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/courier.rb
class Courier < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_attached_file :image
end

app/models/market.rb
class Market < ActiveRecord::Base
end

app/models/market_user.rb
class MarketUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/marketplace.rb
class Marketplace < ActiveRecord::Base
end

app/models/my_courier.rb
class MyCourier < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/td_courier.rb
class TdCourier < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/waybill.rb
class Waybill < ActiveRecord::Base
end

app/controllers/default_pages_controller.rb
class DefaultPagesController < ApplicationController
  def login
    if current_user
      redirect_to persons_profile_url
    else
      render :layout => false
    end

  end

  def market

    render :layout => false
  end
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/default_pages_helper.rb
module DefaultPagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/default_pages/login.html.erb
<% if user_signed_in? %>

    <span>Здравствуйте, <%= current_user.email %></span>

<% else %>
    <%= stylesheet_link_tag    "bootstrap.min",  "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "signin",  "data-turbolinks-track" => true %>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="">

      <title>Signin Template for Bootstrap</title>

      <!-- Bootstrap core CSS -->

      <!-- Custom styles for this template -->


      <!-- Just for debugging purposes. Don't actually copy this line! -->
      <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
    </head>

    <body>

    <div class="container">

      <form class="form-signin" role="form" action="/users/sign_in" method="post" id="new_user">
        <h4 class="form-signin-heading">Авторизуйтесь пожалуйста</h4>
        <input id="user_email" name="user[email]" type="email" class="form-control" placeholder="Email address" required autofocus>
        <input id="user_password" name="user[password]" type="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
          <input name="user[remember_me]" type="checkbox" value="0"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    </body>
    </html>

    <%= link_to 'Зарегистрироваться', new_user_registration_path,  :class => 'btn btn-warning' %>
<% end %>
</div><!--/.nav-collapse -->

app/views/default_pages/market.html.erb
<% if market_user_signed_in? %>

    <span>Здравствуйте, <%= current_user.email %></span>

<% else %>
    <%= stylesheet_link_tag    "bootstrap.min",  "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "signin",  "data-turbolinks-track" => true %>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="">

      <title>Signin Template for Bootstrap</title>

      <!-- Bootstrap core CSS -->

      <!-- Custom styles for this template -->


      <!-- Just for debugging purposes. Don't actually copy this line! -->
      <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
    </head>

    <body>

    <div class="container">

      <form class="form-signin" role="form" action="/market_users/sign_in" method="post" id="new_user">
        <h4 class="form-signin-heading">Авторизуйтесь пожалуйста</h4>
        <input id="market_user_email" name="market_user[email]" type="email" class="form-control" placeholder="Email address" required autofocus>
        <input id="market_user_password" name="market_user[password]" type="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
          <input id="market_user_remember_me" name="market_user[remember_me]" type="checkbox" value="0"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    </body>
    </html>

    <%= link_to 'Зарегистрироваться', new_market_user_registration_path,  :class => 'btn btn-warning' %>
<% end %>
</div><!--/.nav-collapse -->