config/routes.rb
Shopmanager::Application.routes.draw do
  devise_for :market_users
  devise_for :courier_profiles
  devise_for :my_couriers
  devise_for :couriers
  resources :couriers_lists

  resources :curiers_lists

  resources :td_couriers

  resources :waybills_names
  post "waybills_names/add_relation"
  post "waybills_names/remove_relation"
  post "waybills_names/add_auto_courier"
  post "waybills_names/set_status"
  post "waybills_names/get_courier_loc"

  resources :waybills

  get "market_placemanage/main"
  get "market_placemanage/followers"
  get "market_placemanage/orders"
  get "market_placemanage/category_manage"
  get "market_placemanage/item_manage"
  get "market_placemanage/settings"
  get "market_placemanage/courier_manage"
  resources :tags

  get "public_tp/show"
  get "public_tp/trade"
  get "public_tp/review"
  get "market_manage/search_tp"
  get "market_manage/list_td"
  get "market_manage/orders"
  get "market_manage/settings"
  get "market_manage/add_tp"

  resources :card_markets

  resources :card_trading_platforms

  resources :markets

  resources :categories

  resources :items

  resources :types

  resources :orders
  post "orders/add_order"

  resources :couriers

  resources :autos

  get "default_pages/login"
  get "default_pages/market"
  get "market" => "default_pages#market"
  get "trader" => "default_pages#login"
  devise_for :users
  get "persons/profile"
  get "persons/market_profile"
  get "persons/market"
  get "persons/courier"
  get "persons/marketPlace"
  resources :marketplaces

  resources :users

  # The priority is based upon order btn btn-primaryof creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'default_pages#login'

  get 'persons/profile', as: 'user_root'

  get 'persons/market_profile', as: 'market_user_root'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/auto.rb
class Auto < ActiveRecord::Base
end

app/models/c_a_relations.rb
class CARelations < ActiveRecord::Base
end

app/models/card_market.rb
class CardMarket < ActiveRecord::Base
  has_attached_file :avatar
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/courier.rb
class Courier < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/couriers_list.rb
class CouriersList < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_attached_file :image
end

app/models/market.rb
class Market < ActiveRecord::Base
end

app/models/market_user.rb
class MarketUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/marketplace.rb
class Marketplace < ActiveRecord::Base
end

app/models/my_courier.rb
class MyCourier < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/td_courier.rb
class TdCourier < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/waybill.rb
class Waybill < ActiveRecord::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.where(td_id: params[:td_id] , u_id: current_user.id)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.where(id: params[:id] , u_id: current_user.id).take
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @category.parentCat = params[:parentCat]
    @category.td_id = params[:td_id]
    @category.u_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:U_id, :name)
    end
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">
    <%= f.label :Назваие, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Родительская_Категория, :class => 'control-label' %>
    <div class="controls">
      <select name="parentCat">
        <option value="0">Главная</option>
        <% Category.find_all_by_m_id(user_session[:current_trading_place]).each do |p| %>
        <option value="<%= p.id %>"><%= p.name %></option>
        <% end %>
      </select>
    </div>
  </div>

    <input type="hidden" name="td_id" value="<%= params[:td_id] %>">
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:parentCat) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.parentCat %></td>
        <td><%= category.name %></td>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path+'?td_id='+params[:td_id],
            :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>